### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by ferztyle** [micelshima/InfluxDB-Powershell-Module#1]
Hi! I'm very new into the powershell world and i need to install it in windows 2008 boxes, can you provide a tutorial for installing and configuring the modules? Thanks in advance!

Fernando Rios

**Comment by micelshima** [comment]
Hi, you don't install this type of module, it is a regular psm1 file, simply put it in the same path of the script and load it. See any of the examples provided and you will see how I load the file:

#path to script path
$scriptPath = split-path -parent $MyInvocation.MyCommand.Definition
#load influxdb functions
**import-module $scriptPath\influxDBfunctions.psm1**

Edit the psm1 file and change lines 21 and 27 with the **URL of your InfluxDB server**. 
As long as Windows 2008 comes with Powershell 2.0 you will need to install 3.0 or above first because Invoke-webrequest cmdlet is not in 2.0.
If you are lazy about upgrading powershell on servers you can also change a bit the function **write-influxDB** so it sends the data using the yukisagi's function I talk about in readme (Invoke-HttpMethod).
Copying his function inside my module and editing write-InfluxDB like this:

if ($PSVersionTable.PSVersion.Major -lt 3){Invoke-HttpMethod -Uri $url -Body $body -method "Post"}
else{Invoke-webrequest -UseBasicParsing -Uri $url -Body $body -method Post}
